project:
  type: website

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - steering_committee.qmd
      - partners.qmd
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

