---
title: "Code of conduct"
---

<!-- Current version sourced from M Roughan webpage - it's lovely.  -->


We are diverse by nature and inclusive by choice, and the diversity students bring to our university is a resource, strength and benefit.

We aim to support that diversity, and promote equity, among our members and affiliates. Ideally all members and partners, regardless of gender identity or expression, sexual orientation, ethnicity, age, culture, or any other aspect which makes them unique, will feel valued and free to be who they are, as long as that doesn’t impinge on the safety of others, and have an equal chance to reach their full professional potential, and to do great work individually and as part of teams.

The opportunity to speak freely and know that you will be heard, even if not always agreed with, is crucial. Higher education works best when it encourages a vigorous exchange of ideas in which all points of view are heard. And so we must create together a rigorous and lively forum of ideas that is welcoming to everyone. Debate is valuable but we must be careful to approach our discussions with empathy and mutual respect, irrespective of ideology, political views, or identity. We value civility because it permits intellectual, personal, and professional exploration and growth, and we want to make sure those opportunities for exploration and growth include all the members of our community. When we all feel respected and included we can be more creative, innovative, and successful.

We accept that, as flawed human beings, we will at times fall short of our goals. However, we are committed to improve our attempts and identify shortfalls in any event or manner in which we participate. Please get in contact if you know ways to improve the fairness and effectiveness of our shared community of practice