---
title: "Events"
---

## 11th May, 9:30 (online)

**Graph Networks**

## 12th May, 14:10, Engineering North N132

**Kate Helmstedt**

*Mathematics of protecting biodiversity in the GBR, Antarctica, and beyond*

Ecosystems are incredibly complex, and we often have limited or patchy data about them. At the same time, we gain a multitude of benefits from the environment -- needs that are increasing as human populations grow. Sustainable use of the environment can be expensive, and limited funds are available for preserving biodiversity and function. So we have complex, uncertain systems, with a high impetus for protection but resource limitations. Mathematical modelling and decision science are therefore important tools for understanding and protecting environmental systems.

In ecological decision science, we draw from mathematical modelling (social and environmental network models, systems of DEs, Bayesian network models among many more) and operations research (MDPs, spatial prioritisation, sequential decision-making) to tackle these problems. In this talk, I will present work from my research group the Applied Mathematical Ecology Group at QUT focused on applications in the Great Barrier Reef, Antarctica, and threatened species conservation in Australia.


## 15th May, 12:10, SANTOS Petroleum Engineering G04 + Zoom

**Tobin South **

*ChatGPT is the future of data science" & other things people at MIT can't stop staying*

The rise of ChatGPT as a tool for writing data science code follows a long history of tools aims at democratizing data science.  While not the end of coding or data science, it does present a new paradigm of how users can interact with information systems in flexible ways. This talk, featuring a guest project showcase from Peter Moskvichev, will examine how the way organizations, communities, and individuals interact with their data, from LLM data science interfaces, secure community data pools, novel privacy preservation tools, and zero-knowledge proofs. It will feature work from around the MIT Media Lab and will foster some discussion about how translational research can be kicked into overdrive.


## 1 June TBD

**Michele Sasdelli **

## 29 June TBD

**George Stamatescu**


## 29 June TBD

**Tisham Dhar*
